export const copy = {
  brand: "easy4tutor",
  nav: {
    today: "Dzisiaj",
    calendar: "Kalendarz",
    students: "Uczniowie",
    payments: "Płatności",
    statistics: "Statystyki",
    settings: "Ustawienia",
    more: "Więcej",
  },
  actions: {
    addLesson: "Dodaj lekcję",
    planLesson: "Zaplanuj lekcję",
    addStudent: "Dodaj ucznia",
    cancel: "Anuluj",
    saveChanges: "Zapisz zmiany",
    openLesson: "Otwórz lekcję",
    completeLesson: "Oznacz jako uzupełnioną",
    retry: "Spróbuj ponownie",
    undo: "Cofnij",
    archive: "Archiwizuj ucznia",
    restore: "Przywróć ucznia",
    exportCsv: "Eksportuj CSV",
    changeDate: "Zmień termin",
    markPaid: "Oznacz jako opłaconą",
    markUnpaid: "Oznacz jako nieopłaconą",
  },
  status: {
    scheduled: "Zaplanowana",
    needs_completion: "Wymaga uzupełnienia",
    completed: "Uzupełniona",
    cancelled: "Anulowana",
    paid: "Opłacona",
    unpaid: "Nieopłacona",
    present: "Obecny/a",
    absent: "Nieobecny/a",
    unknown: "Nie oznaczono",
    syncFailed: "Błąd synchronizacji",
    deletedGoogle: "Wydarzenie usunięte w Google Calendar",
    notConnected: "Nie połączono",
    notConfigured: "Wymaga konfiguracji",
  },
  empty: {
    students:
      "Nie masz jeszcze uczniów. Dodaj pierwszego ucznia, aby zaplanować lekcję.",
    lessons: "Nie masz jeszcze zaplanowanych lekcji.",
    completed: "Wszystko uzupełnione. Nie masz zaległych lekcji.",
    payments: "Płatności pojawią się po zaplanowaniu pierwszej lekcji.",
  },
  toasts: {
    lessonCreated: "Lekcja zaplanowana",
    lessonsCreated: "Lekcje zaplanowane",
    changesSaved: "Zmiany zapisane",
    studentAdded: "Uczeń dodany",
    studentArchived: "Uczeń zarchiwizowany",
    studentRestored: "Uczeń przywrócony",
    lessonCompleted: "Lekcja uzupełniona",
    paymentChanged: "Status płatności zmieniony",
    dateChanged: "Termin lekcji zmieniony",
  },
  auth: {
    tagline: "Spokojny rytm każdej lekcji.",
    login: "Zaloguj się",
    register: "Załóż konto",
    demo: "Otwórz konto demonstracyjne",
    email: "Adres e-mail",
    password: "Hasło",
    name: "Imię i nazwisko",
    noAccount: "Nie masz jeszcze konta?",
    hasAccount: "Masz już konto?",
  },
} as const;
