import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Check, CheckCircle2, CircleUserRound, Clock3, CreditCard, ExternalLink, FileText, GraduationCap, Link2, Menu, NotebookPen, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { LandingReveal } from "@/components/landing-reveal";
import { formatPrice, monthlyAnnualEquivalentGrosz, PRO_ANNUAL_PRICE_GROSZ, PRO_MONTHLY_PRICE_GROSZ, TRIAL_DAYS } from "@/lib/pricing";
import { currentTeacher } from "@/server/auth";
import styles from "./marketing.module.css";

const days = ["Pon", "Wt", "Śr", "Czw", "Pt"];
function CalendarPreview({ compact = false }: { compact?: boolean }) {
  return <div className={`${styles.calendar} ${compact ? styles.calendarCompact : ""}`}><div className={styles.windowBar}><div><span/><span/><span/></div><strong>Kalendarz</strong><span className={styles.todayPill}>Dzisiaj</span></div><div className={styles.calendarHead}><span/>{days.map((d,i)=><span key={d} className={i===2?styles.activeDay:""}>{d}<b>{12+i}</b></span>)}</div><div className={styles.calendarGrid}><div className={styles.hours}><span>10:00</span><span>12:00</span><span>14:00</span><span>16:00</span></div>{days.map((d,i)=><div className={styles.dayColumn} key={d}>{i===0&&<div className={`${styles.lesson} ${styles.lessonMint}`} style={{top:"12%",height:"26%"}}><b>Ola</b><small>Matematyka</small></div>}{i===1&&<div className={`${styles.lesson} ${styles.lessonBlue}`} style={{top:"48%",height:"28%"}}><b>Grupa B1</b><small>Angielski</small></div>}{i===2&&<div className={`${styles.lesson} ${styles.lessonCoral}`} style={{top:"22%",height:"28%"}}><b>Marta</b><small>14:30 · 60 min</small></div>}{i===3&&<div className={`${styles.lesson} ${styles.lessonBlue}`} style={{top:"8%",height:"24%"}}><b>Adam</b><small>Fizyka</small></div>}{i===4&&<div className={`${styles.lesson} ${styles.lessonMint}`} style={{top:"58%",height:"27%"}}><b>Zosia</b><small>Egzamin 8-kl.</small></div>}</div>)}</div></div>;
}
function HeroProduct(){return <div className={styles.heroStage} aria-label="Podgląd kalendarza i organizacji pracy w Easy4Tutor"><div className={styles.heroGlow}/><CalendarPreview/><div className={`${styles.floatCard} ${styles.studentFloat}`}><span className={styles.avatar}>MK</span><span><small>UCZENNICA</small><b>Marta Kowalska</b><em>Angielski · B1</em></span></div><div className={`${styles.floatCard} ${styles.paymentFloat}`}><span className={styles.iconBox}><WalletCards size={18}/></span><span><small>PAKIET LEKCJI</small><b>6 z 8 wykorzystano</b><i><span/></i></span></div><div className={`${styles.floatCard} ${styles.bookingFloat}`}><CheckCircle2 size={20}/><span><small>NOWA REZERWACJA</small><b>Wtorek, 17:00</b><em>Potwierdzona automatycznie</em></span></div><div className={`${styles.floatCard} ${styles.noteFloat}`}><span className={styles.iconBox}><NotebookPen size={18}/></span><span><small>PO LEKCJI</small><b>Zadanie zapisane</b><em>Ćwiczenia 4–7, str. 38</em></span></div></div>}
function StudentPreview(){return <div className={styles.productPanel}><div className={styles.panelTop}><span className={styles.avatarLarge}>AK</span><div><small>UCZEŃ</small><h3>Adam Kowalski</h3><p>Matematyka · klasa 8</p></div><span className={styles.status}>Aktywny</span></div><div className={styles.statRow}><div><small>NAJBLIŻSZA LEKCJA</small><b>Jutro, 16:00</b></div><div><small>PAKIET</small><b>4 lekcje</b></div><div><small>SALDO</small><b className={styles.green}>Opłacone</b></div></div><div className={styles.memory}><span><Check size={15}/></span><div><small>OSTATNIO</small><b>Równania kwadratowe</b><p>Samodzielnie rozwiązuje deltę. Wrócić do zadań tekstowych.</p></div></div><div className={styles.miniPeople}><div><span>JM</span><b>Grupa: egzamin 8-klasisty</b></div><div><span>+3</span><b>pozostałych uczniów</b></div></div></div>}
function LessonPreview(){return <div className={`${styles.productPanel} ${styles.lessonPanel}`}><div className={styles.lessonNav}><span>← Poprzednia lekcja</span><b>Dzisiejsza lekcja</b><span>Następna →</span></div><div className={styles.lessonTitle}><div><small>MATEMATYKA · ADAM</small><h3>Równania kwadratowe</h3></div><span className={styles.status}>W toku</span></div><div className={styles.tabs}><b>Plan lekcji</b><span>Notatki</span><span>Materiały</span></div><div className={styles.checkList}><p><CheckCircle2 size={17}/> Powtórka wzorów skróconego mnożenia</p><p><CheckCircle2 size={17}/> Równania niezupełne</p><p><span className={styles.emptyCheck}/> Zadania tekstowe</p></div><div className={styles.homework}><NotebookPen size={18}/><span><small>PRACA DOMOWA</small><b>Zadania 6–10 ze zbioru</b></span><span className={styles.saved}>Zapisano</span></div></div>}
function BookingPreview(){return <div className={styles.bookingScene}><div className={styles.phone}><div className={styles.phoneTop}><span className={styles.avatarLarge}>AN</span><div><b>Anna Nowak</b><small>Angielski · online</small></div></div><h3>Umów lekcję</h3><p>Wybierz dogodny termin.</p><div className={styles.dateStrip}><span><small>PON</small>14</span><span className={styles.selectedDate}><small>WT</small>15</span><span><small>ŚR</small>16</span><span><small>CZW</small>17</span></div><div className={styles.timeSlots}><span>15:00</span><b>16:30</b><span>18:00</span></div><div className={styles.bookButton}>Zarezerwuj termin</div></div><div className={styles.confirmCard}><CheckCircle2 size={23}/><span><small>GOTOWE</small><b>Termin zarezerwowany</b><em>15 października · 16:30</em></span></div><div className={styles.shareCard}><Link2 size={17}/><span><small>TWÓJ LINK</small><b>easy4tutor.pl/anna</b></span><ExternalLink size={14}/></div></div>}
const audience=[[CircleUserRound,"Korepetytorzy","Pełny obraz ucznia, lekcji i rozliczeń."],[GraduationCap,"Lektorzy","Grupy, poziomy i materiały zawsze pod ręką."],[UsersRound,"Nauczyciele prywatni","Mniej administracji między zajęciami."]] as const;
const stories=[
  {icon:CalendarDays,kicker:"KALENDARZ I DOSTĘPNOŚĆ",title:"Plan, który nadąża za Twoim tygodniem.",text:"Lekcje indywidualne i grupowe, cykle spotkań, przekładanie terminów oraz dostępność w jednym czytelnym widoku.",points:["Synchronizacja z Google Calendar","Powtarzalne lekcje i blokady czasu","Szybkie przenoszenie terminów"],tone:"blue",visual:<><CalendarPreview compact/><div className={styles.detailFloat}><Clock3 size={18}/><span><small>ŚRODA · 14:30</small><b>Marta · Angielski B1</b><em>60 min · online</em></span></div></>},
  {icon:UsersRound,kicker:"UCZNIOWIE I GRUPY",title:"Pamiętasz więcej, zanim zacznie się lekcja.",text:"Kontakt, poziom, cele, historia spotkań i stan pakietu tworzą jeden profil. Gdy uczeń wraca, cały kontekst już na Ciebie czeka.",points:["Profile uczniów i grup","Historia lekcji i postępów","Najbliższy termin i saldo"],tone:"mint",visual:<StudentPreview/>},
  {icon:BookOpen,kicker:"OBSZAR LEKCJI",title:"Nie tylko administracja. Także samo nauczanie.",text:"Przygotuj plan, prowadź notatki, zaznacz obecność i zadaj pracę domową — bez opuszczania widoku lekcji.",points:["Plan, notatki i materiały","Obecność i podsumowanie","Praca domowa oraz kolejny krok"],tone:"peach",visual:<LessonPreview/>},
  {icon:Link2,kicker:"PUBLICZNE REZERWACJE",title:"Wolny termin trafia prosto do kalendarza.",text:"Udostępnij własny link w bio, na stronie lub w wiadomości. Nowa osoba wybierze rodzaj spotkania i dostępny termin samodzielnie.",points:["Publiczny profil korepetytora","Własne typy spotkań i dostępność","Potwierdzenie i zarządzanie rezerwacją"],tone:"navy",visual:<BookingPreview/>}
] as const;
export default async function LandingPage(){const teacher=await currentTeacher();const appHref=teacher?"/app/dzisiaj":"/rejestracja";const appLabel=teacher?"Przejdź do aplikacji":"Zacznij bezpłatnie";return <main className={styles.page}><LandingReveal>
<header className={styles.header}><div className={styles.navShell}><Link className="brand brand--public" href="/" aria-label="easy4tutor — strona główna"><BrandLogo/></Link><nav className={styles.desktopNav} aria-label="Główna nawigacja"><a href="#funkcje">Funkcje</a><a href="#dla-kogo">Dla korepetytorów</a><a href="#cennik">Cennik</a></nav><div className={styles.navActions}><Link className={styles.login} href="/logowanie">Zaloguj się</Link><Link className={styles.navCta} href={appHref}>{appLabel}<ArrowRight size={15}/></Link></div><details className={styles.mobileMenu}><summary aria-label="Otwórz menu"><Menu size={22}/></summary><div><a href="#funkcje">Funkcje</a><a href="#dla-kogo">Dla korepetytorów</a><a href="#cennik">Cennik</a><Link href="/logowanie">Zaloguj się</Link><Link href={appHref}>{appLabel}</Link></div></details></div></header>
<section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><Sparkles size={14}/> Centrum pracy korepetytora</p><h1>Twoje lekcje.<br/><em>Wreszcie poukładane.</em></h1><p className={styles.lead}>Kalendarz, uczniowie, notatki, rezerwacje i płatności w jednym spokojnym miejscu. Ty skupiasz się na nauczaniu — Easy4Tutor pilnuje reszty.</p><div className={styles.heroActions}><Link className={styles.primaryButton} href={appHref}>{appLabel}<ArrowRight size={18}/></Link><a className={styles.secondaryButton} href="#funkcje">Zobacz, jak działa</a></div>{!teacher&&<p className={styles.trust}><Check size={15}/>{TRIAL_DAYS} dni Pro bez karty · potem możesz zostać na Free</p>}</div><HeroProduct/></section>
<section className={styles.audience} id="dla-kogo" data-reveal><p className={styles.audienceLead}>Dla osób, które uczą <strong>po swojemu</strong> — ale chcą organizować pracę profesjonalnie.</p><div className={styles.audienceItems}>{audience.map(([Icon,title,text])=><article key={title}><Icon size={22}/><span><b>{title}</b><small>{text}</small></span></article>)}</div></section>
<section className={styles.story} id="funkcje"><div className={styles.sectionHeading} data-reveal><p className={styles.eyebrow}>Jeden system, cały dzień</p><h2>Każdy element pracy<br/>łączy się z następnym.</h2><p>Bez przepisywania terminów, szukania notatek i sprawdzania kilku aplikacji przed zajęciami.</p></div>{stories.map((s,i)=><article className={`${styles.feature} ${i%2?styles.reverse:""}`} data-reveal key={s.kicker}><div className={styles.featureCopy}><span className={styles.featureIcon}><s.icon size={20}/></span><p className={styles.kicker}>{s.kicker}</p><h2>{s.title}</h2><p>{s.text}</p><ul>{s.points.map(p=><li key={p}><Check/>{p}</li>)}</ul></div><div className={`${styles.featureVisual} ${styles[`${s.tone}Visual`]}`}>{s.visual}</div></article>)}</section>
<section className={styles.workflow} data-reveal><div className={styles.workflowIntro}><p className={styles.eyebrow}>Jeden przepływ</p><h2>Od pierwszej rezerwacji<br/>do rozliczonej lekcji.</h2><p>Pięć etapów, jeden ciąg informacji. Nic nie ginie po drodze.</p></div><div className={styles.flowLine}>{[[CircleUserRound,"Nowy uczeń","Kontakt i cel nauki"],[CalendarDays,"Rezerwacja","Wybrany wolny termin"],[BookOpen,"Lekcja","Plan i obecność"],[FileText,"Notatki","Postęp i praca domowa"],[CreditCard,"Rozliczenie","Płatność lub pakiet"]].map(([Icon,title,text],i)=><div className={styles.flowStep} key={title as string}><span className={styles.flowNumber}>0{i+1}</span><span className={styles.flowIcon}><Icon size={20}/></span><b>{title as string}</b><small>{text as string}</small></div>)}</div></section>
<section className={styles.benefits} data-reveal><div><p className={styles.eyebrow}>Mniej narzędzi. Więcej ciągłości.</p><h2>Spokojniejsza głowa między lekcjami.</h2></div><div className={styles.benefitGrid}><article><b>01</b><h3>Wiesz, co jest następne</h3><p>Plan dnia, najbliższa lekcja i ważny kontekst są widoczne od razu.</p></article><article><b>02</b><h3>Nie przepisujesz danych</h3><p>Rezerwacja staje się lekcją, lekcja historią, a pakiet aktualizuje się razem z nią.</p></article><article><b>03</b><h3>Uczeń widzi profesjonalną obsługę</h3><p>Prosty link do zapisów, jasne terminy i uporządkowana współpraca od początku.</p></article></div></section>
<section className={styles.pricing} id="cennik" data-reveal><div className={styles.pricingCopy}><p className={styles.eyebrow}>Prosty cennik</p><h2>Zacznij bez presji.<br/>Rozwijaj się we własnym tempie.</h2><p>Najpierw {TRIAL_DAYS} dni pełnego planu Pro bez karty. Później wybierasz: bezpłatny plan Free albo Pro bez limitu uczniów.</p><Link className={styles.textLink} href="/rejestracja">Załóż bezpłatne konto <ArrowRight size={16}/></Link></div><div className={styles.priceCards}><article><span>FREE</span><h3>0 zł</h3><p>Na start i do 3 aktywnych uczniów.</p><ul><li><Check/>Kalendarz i dostępność</li><li><Check/>Lekcje, notatki i zadania</li><li><Check/>Płatności i pakiety</li></ul></article><article className={styles.proCard}><span>PRO · {TRIAL_DAYS} DNI GRATIS</span><h3>{formatPrice(PRO_MONTHLY_PRICE_GROSZ)} <small>/ mies.</small></h3><p>Bez limitu uczniów i z automatyzacjami.</p><ul><li><Check/>Wszystko z planu Free</li><li><Check/>Google Calendar i przypomnienia</li><li><Check/>Od {formatPrice(monthlyAnnualEquivalentGrosz())}/mies. przy płatności {formatPrice(PRO_ANNUAL_PRICE_GROSZ)}/rok</li></ul><Link href={appHref}>Wypróbuj Pro <ArrowRight size={16}/></Link></article></div></section>
<section className={styles.finalCta} data-reveal><div><p className={styles.eyebrow}>Twój następny dzień może być prostszy</p><h2>Wszystko gotowe<br/>na kolejną lekcję.</h2><p>Zacznij od uporządkowania kalendarza. Reszta połączy się po drodze.</p></div><Link href={appHref}>{appLabel}<ArrowRight size={19}/></Link></section>
<footer className={styles.footer}><div><Link className="brand brand--public" href="/" aria-label="easy4tutor — strona główna"><BrandLogo/></Link><p>Jedno miejsce do prowadzenia korepetycji.</p></div><nav aria-label="Stopka"><div><b>Produkt</b><a href="#funkcje">Funkcje</a><a href="#cennik">Cennik</a><Link href="/logowanie">Logowanie</Link></div><div><b>Informacje</b><Link href="/polityka-prywatnosci">Polityka prywatności</Link><Link href="/regulamin">Regulamin</Link></div></nav><p className={styles.copyright}>© 2026 easy4tutor</p></footer>
</LandingReveal></main>}
